//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILDMS.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SILDMS.Model.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Failed..
        /// </summary>
        public static string E401 {
            get {
                return ResourceManager.GetString("E401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Failed..
        /// </summary>
        public static string E402 {
            get {
                return ResourceManager.GetString("E402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Failed..
        /// </summary>
        public static string E403 {
            get {
                return ResourceManager.GetString("E403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Validation Failed..
        /// </summary>
        public static string E404 {
            get {
                return ResourceManager.GetString("E404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Already Exist..
        /// </summary>
        public static string E405 {
            get {
                return ResourceManager.GetString("E405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocurrency Occured. Please Try Again Later..
        /// </summary>
        public static string E406 {
            get {
                return ResourceManager.GetString("E406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User suspended..
        /// </summary>
        public static string E407 {
            get {
                return ResourceManager.GetString("E407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password..
        /// </summary>
        public static string E408 {
            get {
                return ResourceManager.GetString("E408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not authorized to perform this action. .
        /// </summary>
        public static string E409 {
            get {
                return ResourceManager.GetString("E409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same user name already exist. Please try with different name..
        /// </summary>
        public static string E410 {
            get {
                return ResourceManager.GetString("E410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No column name match with property name. Please upload valid excel file..
        /// </summary>
        public static string E411 {
            get {
                return ResourceManager.GetString("E411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully..
        /// </summary>
        public static string S201 {
            get {
                return ResourceManager.GetString("S201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Updated Successfully..
        /// </summary>
        public static string S202 {
            get {
                return ResourceManager.GetString("S202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Deleted Successfully..
        /// </summary>
        public static string S203 {
            get {
                return ResourceManager.GetString("S203", resourceCulture);
            }
        }
    }
}
